[package]
name = "card_printer"
version = "0.1.0"
authors = ["storyfeet <thebeaky@psmail.net>"]
edition = "2018"

[dependencies]
lazyf = { path = "../../mlibs/lazyf"}
mksvg = { path = "../../mlibs/mksvg"}
